# Generated by Django 5.1.2 on 2024-11-23 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='image',
            field=models.ImageField(blank=True, default='image.png', upload_to=''),
        ),
    ]
