# Generated by Django 5.1.2 on 2024-11-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0002_alter_inmueble_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
