# Generated by Django 5.1.2 on 2024-11-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0005_alter_inmueble_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
